AREA OF CRICLE 
value = input('enter value of radius')
pi = 3.14
area = pi * float(value) ** 2
print(f"area of circle is {area}")

AREA OF RECTANGLE

length = int(input('enter value of length'))
breadth = int(input('enter value of breadth'))
area = length * breadth
print(f"area of rectangle {area}")

AREA OF TRAINGLE

base = int(input('enter the value of base'))
height = int(input('enter the value of height'))
area = 1/2 * base * height
print(f"area of triangle {area}")
